//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    [global::System.Data.Linq.Mapping.TableAttribute(Name ="db.Accessori")]
    public partial class accessorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accessorio()
        {
            this.servizios = new HashSet<servizio>();
        }
    
        public string Tipologia { get; set; }
        public System.DateTime UltimoControllo { get; set; }
        public string Produttore { get; set; }
        public string Taglia { get; set; }
        public string IDaccessorio { get; set; }
        public string IDmagazzino { get; set; }
    
        public virtual magazzino magazzino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servizio> servizios { get; set; }
    }
}
