//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseTestWFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class bicicletta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bicicletta()
        {
            this.servizios = new HashSet<servizio>();
        }
    
        public string Produttore { get; set; }
        public string NumTelaio { get; set; }
        public string Taglia { get; set; }
        public int RaggioRuota { get; set; }
        public string Tipologia { get; set; }
        public System.DateTime UltimoControllo { get; set; }
        public int NumRapportiAnteriori { get; set; }
        public int NumRapportiPosteriori { get; set; }
        public sbyte isElettrica { get; set; }
        public Nullable<int> PotenzaBatteria { get; set; }
        public Nullable<int> CapacitàBatteria { get; set; }
        public string IDmagazzino { get; set; }
    
        public virtual magazzino magazzino { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servizio> servizios { get; set; }
    }
}
