//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class dipendente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dipendente()
        {
            this.gerarchias = new HashSet<gerarchia>();
            this.tours = new HashSet<tour>();
            this.servizios = new HashSet<servizio>();
        }
    
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string CF { get; set; }
        public string Recapito { get; set; }
        public string CodiceDipendente { get; set; }
        public float Stipendio { get; set; }
        public string isGuida { get; set; }
        public string isTourManager { get; set; }
        public string isAltro { get; set; }
        public string IDsede { get; set; }
    
        public virtual sede sede { get; set; }
        public virtual gerarchia gerarchia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<gerarchia> gerarchias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tour> tours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servizio> servizios { get; set; }
    }
}
