//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseTestWFA
{
    using System;
    using System.Collections.Generic;
    
    public partial class dipendente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dipendente()
        {
            this.dipendente1 = new HashSet<dipendente>();
            this.tours = new HashSet<tour>();
            this.servizios = new HashSet<servizio>();
        }
    
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string CF { get; set; }
        public string Recapito { get; set; }
        public string CodiceDipendente { get; set; }
        public float Stipendio { get; set; }
        public sbyte isGuida { get; set; }
        public sbyte isTourManager { get; set; }
        public sbyte isAltro { get; set; }
        public string IDsede { get; set; }
        public string CFsuperiore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dipendente> dipendente1 { get; set; }
        public virtual dipendente dipendente2 { get; set; }
        public virtual sede sede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tour> tours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<servizio> servizios { get; set; }
    }
}
