//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseTestWFA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gestionale_per_agenzie_relEntities1 : DbContext
    {
        public gestionale_per_agenzie_relEntities1()
            : base("name=gestionale_per_agenzie_relEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accessorio> accessorios { get; set; }
        public virtual DbSet<agenzia> agenzias { get; set; }
        public virtual DbSet<attrazione> attraziones { get; set; }
        public virtual DbSet<bicicletta> biciclettas { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<dipendente> dipendentes { get; set; }
        public virtual DbSet<gerarchia> gerarchias { get; set; }
        public virtual DbSet<indirizzo> indirizzoes { get; set; }
        public virtual DbSet<magazzino> magazzinoes { get; set; }
        public virtual DbSet<pacchetto> pacchettoes { get; set; }
        public virtual DbSet<percorso> percorsoes { get; set; }
        public virtual DbSet<ristorante> ristorantes { get; set; }
        public virtual DbSet<sede> sedes { get; set; }
        public virtual DbSet<sequenza> sequenzas { get; set; }
        public virtual DbSet<servizio> servizios { get; set; }
        public virtual DbSet<soggiorno> soggiornoes { get; set; }
        public virtual DbSet<tappa> tappas { get; set; }
        public virtual DbSet<tour> tours { get; set; }
    }
}
